### ISSUE TITLE
Issue with api

### ISSUE THREAD

**Issue by ZachZuk** [CyberTimon/Powerpointer-For-Local-LLMs#8]
I first run the text generation api, then I try to run powerpointer.py, and I get an error with the api. When I navigate to the 5000 local host manually, it shows a json object saying method not allowed. Here is the actual error I am getting:

Traceback (most recent call last):
  File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 152, in <module>
    main()
  File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 148, in main
    print ("Generated and saved under:", generate_ppt(topic, add_info, slides, theme))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 133, in generate_ppt
    f.write(create_ppt_text(prompt, slides, add_info))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 52, in create_ppt_text
    result = response.json()['results'][0]['text']
             ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'results'

and this is what I get if I print out response.json first:

{'detail': 'Not Found'}

**Comment by CyberTimon** [comment]
Hi

Thank you for your interest in this Powerpoint generator and I'm sorry it's causing errors.

I can't reproduce this error for me. It seems like other people have a similar problem: https://www.reddit.com/r/Oobabooga/comments/18hfpu9/i_get_detail_not_found_when_prompting_over_api/

What loader are you using and are you using the latest version?

Best regards,
Timon

**Comment by jasonsi1993** [comment]
> I first run the text generation api, then I try to run powerpointer.py, and I get an error with the api. When I navigate to the 5000 local host manually, it shows a json object saying method not allowed. Here is the actual error I am getting:
> 
> Traceback (most recent call last): File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 152, in main() File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 148, in main print ("Generated and saved under:", generate_ppt(topic, add_info, slides, theme)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 133, in generate_ppt f.write(create_ppt_text(prompt, slides, add_info)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\zachy\Documents\GitHub\Powerpointer-For-Local-LLMs\powerpointer.py", line 52, in create_ppt_text result = response.json()['results'][0]['text'] ~~~~~~~~~~~~~~~^^^^^^^^^^^ KeyError: 'results'
> 
> and this is what I get if I print out response.json first:
> 
> {'detail': 'Not Found'}

Did you find a solution to this at the end?

**Comment by jasonsi1993** [comment]
Thank you for the response. It will be a great change, i have a custom llama.cpp repo that is fine tuned for the hardware i am running. Using the native llama.cpp server would be a lot easier for me to integrate. Looking forward for the upcoming update.

**Comment by CyberTimon** [comment]
Update is here now. It fully supports OpenAI format compatible endpoints. Have fun!
@jasonsi1993
